name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for raising a issue, Hope you enjoing the open source. I'm sorry to inform you that this project got excluded from Hacktoberfest-2024 your contribution will not be counted. If you still wants to contribute please go-ahead."
